### PR TITLE
Fixed the unwanted text error

### LINKED ISSUE #110: Unwanted text appeared
Want to correct this bug of getting unwanted text,

When we add expedition/deduction > income, 
below window appears

and at this time if we decrease the value of expedition/deduction such that it become less than income, and press calculate button,
we get this unwanted text, shown below,

### PR DESCRIPTION
**Pull request by akash-rajak**
#### Issue Number
fixes #110

#### Describe the changes you've made
Fixed the bug in code showing unwanted text.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

Below shows the screenshot of corrected output,

Now in below image we don't see any unwanted text,

### CODE REVIEW

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , i have corrected the issue, please check it.

**Comment by QAZIMAAZARSHAD** [comment]
Download the updated file https://github.com/QAZIMAAZARSHAD/Income-Tax-Calcultor/archive/refs/heads/main.zip

Check it is already not there.

**Comment by akash-rajak** [comment]
It's there, just do like this
when income entering page opens
first add input such that income < expedition/deduction
when we add like this we get following output,


Now don't clear anything in this page, just decrease the value of expedition/deduction such that expedition/deduction become less than income, and now if we calculate, we get those text, like this,



Also can see in below video,

https://user-images.githubusercontent.com/57003737/122101026-7b29fa00-ce31-11eb-9d9e-94a65de9628c.mp4

**Comment by akash-rajak** [comment]
sorry closed the pr by mistake, i shown the methods when we get those unwanted text, please see it

**Pull request merged**
