### PR TITLE
Added Splash screen

### LINKED ISSUE #1: Create a splash screen when application opens
A splash screen with the logo of application must appear for 5 seconds when the application start then it should automatically close and then the home page window should appear.

https://cdn.dribbble.com/users/164756/screenshots/14613561/netflix-800x600-with-logo.gif

The splash screen should be like this.

### PR DESCRIPTION
**Pull request by akash-rajak**
#### Issue Number
fixes #1

#### Describe the changes you've made
- Added splash.gif to show on splash screen
- Implemented the code to display the splash screen for 5 sec and then opens the starting page of income tax calculator
- Also implmented the exit dialog box for splash window also, means if we try to close the splash window, we get exit dialog box for asking permission. 
- Also added the icon of final_logo that was beside the title of all frame, also on the splash window.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

To see how it works see below video,

https://user-images.githubusercontent.com/57003737/122204979-5bd8ae80-cebd-11eb-96e8-b2695fed0191.mp4

### CODE REVIEW

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , I created the pr for adding splash screen whwn the application opens, please check it.

**Comment by QAZIMAAZARSHAD** [comment]
Too many unnecessary changes.

Try to correct it or make a new PR. Not possible to review.

**Comment by akash-rajak** [comment]
Can i close this pr as created new one?

**Comment by QAZIMAAZARSHAD** [comment]
> Can i close this pr as created new one?

Yes always do that.

**Pull request closed without merging**
