### PR TITLE
Reset button not vanishing income/deductions input 

### LINKED ISSUE #2: Change logo in title bar
image

### PR DESCRIPTION
**Pull request by ShreyaKanodia**
#### Issue #9 
fixes 2

#### Describe the changes you've made
In delete function I have entered two statements to delete value entered in Income and Deductions so that when reset button is pressed those two inputs are also delete.

But delete function is also called in in calculate function.
The purpose of calling delete function in calculate function was to clear Tax calculated in previous result and show white space for new result.
so I removed the delete function and just added the purpose.
I did this because new delete function is clearing input of income and deductions, which is not desirable in calculate function 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@ShreyaKanodia Why you have mentioned issue number 2 in the description.
Edit your comment.

I'll review your PR soon.

**Comment by ShreyaKanodia** [comment]
@QAZIMAAZARSHAD  Sorry it was by mistake.
Could you please explain me about checklist, I am not getting that

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Sorry it was by mistake.
> Could you please explain to me about the checklist, I am not getting that

Tick the boxes which are true in the case of your PR. See 👇
image

**Comment by QAZIMAAZARSHAD** [comment]
Application not working after your changes.

Retry.

**Pull request closed without merging**
