### PR TITLE
Fixed issue regarding validating user input in Annual Tax and Exemptions

### PR DESCRIPTION
**Pull request by Prateek027-S**
#### Issue Number 49
fixes #
ISSUE #49

#### Describe the changes you've made
I have used Regular expressions to validate the user input. If the user enters invalid input, then an error message-box shows up.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(LGMSOC'21)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
340 addition and  333 deletions. Do something about it.
Only necessary changes should highlight.

Not possible to review.

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by QAZIMAAZARSHAD** [comment]
+357 −348  additions and deletions.

Do something about this as well.
Create a new PR it will be better.

**Comment by Prateek027-S** [comment]
okay, I will create a new PR. And close this PR.

**Pull request closed without merging**
