### PR TITLE
Email Functionality

### PR DESCRIPTION
**Pull request by Khushijindal24**
#63 
fixes 

#### Describe the changes you've made
I have created share with mail button with the help of it we can send the tax calculation information to the user using smtplib concept.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x ] I have added my name in the contributors list at the end of README.md file.
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Application crashing after changes.

Every line is fine, but as soon as I add this line the application crashes -> "s.starttls()".

**Comment by jigar-sable** [comment]
> Application crashing after changes.
> 
> Every line is fine, but as soon as I add this line the application crashes -> "s.starttls()".

@QAZIMAAZARSHAD its working well.. I'd checked it I receive the mail too.
Due to SMTP server it takes some time maybe 3-4sec but surely mail will be sended to the id which user enters.

**Comment by QAZIMAAZARSHAD** [comment]
> > Application crashing after changes.
> > Every line is fine, but as soon as I add this line the application crashes -> "s.starttls()".
> 
> @QAZIMAAZARSHAD its working well.. I'd checked it I receive the mail too.
> Due to SMTP server it takes some time maybe 3-4sec but surely mail will be sended to the id which user enters.

No problem in the mail, the application is crashing by these changes. (Not opening).

**Comment by jigar-sable** [comment]
> > > Application crashing after changes.
> > > Every line is fine, but as soon as I add this line the application crashes -> "s.starttls()".
> > 
> > 
> > @QAZIMAAZARSHAD its working well.. I'd checked it I receive the mail too.
> > Due to SMTP server it takes some time maybe 3-4sec but surely mail will be sended to the id which user enters.
> 
> No problem in the mail, the application is crashing by these changes. (Not opening).

Please share the error logs snapshots..

**Comment by QAZIMAAZARSHAD** [comment]
> > > > Application crashing after changes.
> > > > Every line is fine, but as soon as I add this line the application crashes -> "s.starttls()".
> > > 
> > > 
> > > @QAZIMAAZARSHAD its working well.. I'd checked it I receive the mail too.
> > > Due to SMTP server it takes some time maybe 3-4sec but surely mail will be sended to the id which user enters.
> > 
> > 
> > No problem in the mail, the application is crashing by these changes. (Not opening).
> 
> Please share the error logs snapshots..

can't it closes within mili-seconds, can't see the error code.

**Comment by jigar-sable** [comment]
Oh that's why I mention it earlier that it takes 3-4sec to send mail due to SMTP Server. Also the id used here is not of gmail so its not faster too. 
Suggested show the message prompt after sending mail and clear all IO. Either show loader as sending mail like that.

**Pull request merged**
