### PR TITLE
Updated the project with PDF Generator

### PR DESCRIPTION
**Pull request by rammya29**
LMG-SoC : Participant

#### Issue Number : 132
fixes #

#### Describe the changes you've made

The changes are like added a new button PDF for generating PDF Reports. I added a new image background for PDF in the format of png.

#### Describe if there is any unusual behavior of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?
     They can download the application and run it using any idle. I have tested my code using the same method

#### Checklist

- [ ] I have added my name to the contributor's list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) - Let's Grow More - Soc Participant

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Not working!!!
You forgot to upload the image
Screenshot (146)

Screenshot (147)
Also, the button becomes invisible when the result is displayed.

**Comment by QAZIMAAZARSHAD** [comment]
Always mention the issue number like this #132.

And you have wrong issue number.

**Comment by rammya29** [comment]
I can't upload images from your repository. Can I attach the image in this comment

**Comment by rammya29** [comment]
Image

This is image i have to upload

**Comment by QAZIMAAZARSHAD** [comment]
> Image
> 
> This is image i have to upload

Go to your branch with which you are making PR.

Then click on upload files, select the image from your desktop then commit changes.

image

**Comment by QAZIMAAZARSHAD** [comment]
Okk I will upload the image.

**Pull request merged**
