### PR TITLE
Solution for #88

### PR DESCRIPTION
**Pull request by shantamsultania**
Reformatted the Code to Standard Python conventions and in a document like View fixes.

Done :

1. Code Reformatting 
2. To Python conversions

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Always mention issue number like this #88

**Comment by shantamsultania** [comment]
hey, @QAZIMAAZARSHAD I have done the code reformatting as mentioned in issue #88  I will insist that you first merge this code and then only other codes should be merged to avoid merge conflicts.

**Comment by shantamsultania** [comment]
> Always mention issue number like this #88

I was just writing the comments 😜

**Comment by QAZIMAAZARSHAD** [comment]
Application crashing after these changes.

Review once again.

**Comment by shantamsultania** [comment]
can you can share errors if any ?

**Comment by shantamsultania** [comment]
check now 
i by mistakenly changes the old_tax to new_tax to old and new just a silly mistake

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by shantamsultania** [comment]
All conflicts have been resolved

**Comment by QAZIMAAZARSHAD** [comment]
Also, you have shifted all the buttons together at the bottom, I don't think this is a nice idea they should be near the function. It's confusing a bit if they all are at the bottom.

**Comment by QAZIMAAZARSHAD** [comment]
> All conflicts have been resolved

no 

check again
 I cannot merge your PR.

**Comment by shantamsultania** [comment]
Ok let me take a look 

About shifting the buttons in the bottom i did taht accordingly to the python standard code formation 
In this all the functions are always on top and then ui / main classes

**Comment by QAZIMAAZARSHAD** [comment]
> Ok let me take a look
> 
> About shifting the buttons in the bottom i did taht accordingly to the python standard code formation
> In this all the functions are always on top and then ui / main classes

Oo, I had no idea about that.

**Comment by shantamsultania** [comment]
Basically this will give the code a documentation like read 

You will read all the features first 
Then go to calling the features and stuff or ui

**Comment by shantamsultania** [comment]
And about the working check i will check it again once but as i checked earlier it was working fine as expected .

**Comment by shantamsultania** [comment]
hey @QAZIMAAZARSHAD i am creating a new PR the reason for this merge conflict was that some of the other PRS were merged and they required some changes so I have not done too much of code formating just did the naming conventions and space reformating.

**Pull request closed without merging**
