### PR TITLE
Wrong result when taxable income becomes too large

### PR DESCRIPTION
**Pull request by ShreyaKanodia**
#### ISSUE #10 
fixes # 2

#### Describe the changes you've made
In old tax function ,
after n==4 , now there is no need to break salary into divisions of 2,50,000 so applied a tax of 30% on total salary left at n==4 and then applied break
in case of new tax function,
after n==6,now there is no need to break salary into divisions of 2,50,000 so applied a tax of 30% on total salary left at n==6 and then applied break.

in previous code the bug was that if income  became extra large, then n becomes greater than 6 and hence 'else' statement was executed and thus total was showing zero

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@ShreyaKanodia why you closed this PR?

**Comment by QAZIMAAZARSHAD** [comment]
@ShreyaKanodia while making PR you have to always mention the issue number in the PR description.

Edit your PR description with related issue number.

**Comment by ShreyaKanodia** [comment]
@QAZIMAAZARSHAD  should I close the pull request and then reopen it after 12'o clock today midnight for LGMSoC or it will be considered now only

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD should I close the pull request and then reopen it after 12'o clock today midnight for LGMSoC or it will be considered now only

Leave it,
I will merge your PR tomorrow. Points depend on the day the PR is merged not on the day it is made.

**Comment by ShreyaKanodia** [comment]
@QAZIMAAZARSHAD  Ok thanks a lot,
Are there any other changes  required ?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Ok thanks a lot,
> Are there any other changes required?

If you believe there is any scope of improvement then sure, go ahead.

**Pull request merged**
