### PR TITLE
Added i label showing the valid entry example

### LINKED ISSUE #107: i label to see valid data
Want to add i label to showing eg. of  valid entry which can be entered, 
eg. valid names, valid number , valid email id

it will look like this, on clicking on i label, we get this information

### PR DESCRIPTION
**Pull request by akash-rajak**
#### Issue Number
fixes #107

#### Describe the changes you've made
Added the i label clicking on which shows the valid entry examples.
Also decreased the size of i label, as asked.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

Below shows the image of changes done,

### CODE REVIEW

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , created a pr for adding i label, please check it

**Comment by QAZIMAAZARSHAD** [comment]
Application crashed after your changes.

**Comment by akash-rajak** [comment]
it's running fine on my pc, application working same as earlier
Can you please tell me, application crashes on doing which step, or any error it is showing?

**Comment by QAZIMAAZARSHAD** [comment]
It's creating a problem for me, try another approach.

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , earlier i was using i button as image, i changed it to button now, please check it,
let me know if any error

**Pull request merged**
