### PR TITLE
Email Functionality

### PR DESCRIPTION
**Pull request by Khushijindal24**
#63 
fixes #

#### Describe the changes you've made
I have created a share with mail button , by clicking on it , a pop up message appear about confirming the info and the tax calculated and by clicking on it we can share the info through mail by using concept of smtplib_ssl

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by Khushijindal24** [comment]
sir i have merged the new pull request.

**Comment by QAZIMAAZARSHAD** [comment]
Whenever make a new PR delete old one.

**Comment by Khushijindal24** [comment]
> Whenever make a new PR delete old one.

ok sir
please check #113 email functionality

**Pull request closed without merging**
