### PR TITLE
Added logo in readme

### LINKED ISSUE #142: Add final logo in readme
A project should have the logo displayed in the readme so that it has an identity.

### PR DESCRIPTION
**Pull request by supzi-del**
#### Issue Number
fixes #142 

#### Describe the changes you've made
Added the final logo on top of the readme file.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(LGMSOC'21)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Not looking good!!!!

Remove it from there and add it in about section like this ->
image

**Comment by QAZIMAAZARSHAD** [comment]
Compress the size of the logo accordingly.

**Comment by supzi-del** [comment]
image

**Comment by supzi-del** [comment]
Like this?

**Comment by supzi-del** [comment]
image

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

**Pull request merged**
