### PR TITLE
Added splash screen when application opens

### LINKED ISSUE #1: Create a splash screen when application opens
A splash screen with the logo of application must appear for 5 seconds when the application start then it should automatically close and then the home page window should appear.

https://cdn.dribbble.com/users/164756/screenshots/14613561/netflix-800x600-with-logo.gif

The splash screen should be like this.

### PR DESCRIPTION
**Pull request by akash-rajak**
#### Issue Number
fixes #1

#### Describe the changes you've made
- Added splash.gif to show on splash screen
- Implemented the code to display the splash screen for 5 sec and then opens the starting page of income tax calculator
- Also implmented the exit dialog box for splash window also, means if we try to close the splash window, we get exit dialog box for asking permission. 
- Also added the icon of final_logo that was beside the title of all frame, also on the splash window.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , created the new pr, but in this also same thing is there. This large no. of addition and deletion will definintely happen, because i am defining a function , and moving most almost all the previous code to that function,

And it is necessary to define function before calling ,so need to define it at the top, so indirectly moving bulk of code to top main_window() function.

In this to add splash screen , it only takes 20 to 25 lines to in moving bulk of code , large no. of addition deletion takes place.

**Comment by QAZIMAAZARSHAD** [comment]
It will take a lot of time to review.

**Comment by akash-rajak** [comment]
can i tell the steps what it have done, so it will be easy?

**Comment by QAZIMAAZARSHAD** [comment]
> can i tell the steps what it have done, so it will be easy?

No, while reviewing PR I have to take into account every single addition and deletions, if something went wrong it may disturb few features or in the worst case may corrupt the entire application.

Try something if you can improve.

**Comment by akash-rajak** [comment]
this is the simplest approach i guess . if possible can i send you the code.

**Comment by akash-rajak** [comment]
are you trying to review it or anything else?

**Comment by QAZIMAAZARSHAD** [comment]
> are you trying to review it or anything else?

I Will review it later.

**Comment by akash-rajak** [comment]
ok thnx, if any issue in reviewing you can ask me

**Comment by QAZIMAAZARSHAD** [comment]
Application crashed after your changes.

Review again, Make a clean PR.

**Pull request closed without merging**
