### PR TITLE
Fixed User Details Validation

### LINKED ISSUE #4: Validate user details form
image

Form must not accept wrong inputs like :
Name = k56% 
Contact = 983@gmajdk83hf\
Email = jdhd8h#$%

A warning must appear when a user makes illegal inputs.

### PR DESCRIPTION
**Pull request by hellosafwaan**
#### Issue Number
fixes #4 

#### Describe the changes you've made
* Used RegEx module to find matching pattern for Name, Contact & Email ID.
* If a user enters invalid details (which is not recognized by the pattern specified in program) such as name, number, email id, the user is prompted with an error. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names (LGM-SOC)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by hellosafwaan** [comment]
Working on it.

**Comment by hellosafwaan** [comment]
check it @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Nope.

Fetch upstream. Try with a separate branch.

**Pull request closed without merging**
