### PR TITLE
updated Solution for #88 code reformating 

### LINKED ISSUE #88: Code formating
I have a Suggestion to make to reformate the code to standard naming conventions for python.

Reason :

Many of the participants are beginners so I think it will be good if we can reformate the code to some extent like some variables are named f1,f2, and so on we can convert the name to frame1,frame2, and so on.

If possible can i can take this to make the code more readable? under LGM-SOC-21

### PR DESCRIPTION
**Pull request by shantamsultania**
implemented Code Reformatting and changed Variable names to standard Python naming convestions

This fixes #88

### CODE REVIEW

**Comment by shantamsultania** [comment]
hey @QAZIMAAZARSHAD I had to close down the previous one due to some merge conflicts. I have checked it's working fine no errors are there I didn't change the functions to the top and kept buttons at last as you said it may create some issues. 

I hope this time it will not create any issues.

**Comment by QAZIMAAZARSHAD** [comment]
Application again crashed after your changes.

**Comment by QAZIMAAZARSHAD** [comment]
I think let's close this issue here.

Also, it takes a lot of time in reviewing these kinds of changes.

**Comment by shantamsultania** [comment]
> I think let's close this issue here.
> 
> Also, it takes a lot of time in reviewing these kinds of changes.

ok, no issues I completely understand but if possible can you can share what was the exact error being displayed as I double-checked all was ok from my side. the application was working fine

**Comment by QAZIMAAZARSHAD** [comment]
> > I think let's close this issue here.
> > Also, it takes a lot of time in reviewing these kinds of changes.
> 
> ok, no issues I completely understand but if possible can you can share what was the exact error being displayed as I double-checked all was ok from my side. the application was working fine

No error,


The application crashed after the changes. Opens only for a second.

**Comment by shantamsultania** [comment]
> > > I think let's close this issue here.
> > > Also, it takes a lot of time in reviewing these kinds of changes.
> > 
> > 
> > ok, no issues I completely understand but if possible can you can share what was the exact error being displayed as I double-checked all was ok from my side. the application was working fine
> 
> No error,
> 
> The application crashed after the changes. Opens only for a second.

ok cool will try to find out the main reason for this also and try to be more careful in the future regarding the same.

**Pull request closed without merging**
