### PR TITLE
Fixed the issue about validating the Annual Tax and Exemptions.

### PR DESCRIPTION
**Pull request by Prateek027-S**
#### Issue Number 49
fixes #
ISSUE #49

#### Describe the changes you've made
I have used Regular expressions to validate the user input. If the user enters invalid input, then an error message-box shows up.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
By leaving the input fields of Annual Tax  and Exemptions empty, or by writing invalid input such as character instead of numbers, and then clicking the Calculate button.

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program names(LGMSOC'21)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Update your repo.

Also, too many unnecessary indentation changes also spelling mistake.

**Comment by QAZIMAAZARSHAD** [comment]
Still same.

**Comment by Prateek027-S** [comment]
> Still same.

Now I have updated my repo. So, is it giving some kind of error?

**Comment by QAZIMAAZARSHAD** [comment]
> > Still same.
> 
> Now I have updated my repo. So, is it giving some kind of error?

No error application is not even starting.

**Comment by QAZIMAAZARSHAD** [comment]
It might be working in your system but we can't accept a solution that is not a solution for everyone.

Try another approach,

**Pull request closed without merging**
