### PR TITLE
Update pull_request_template.md

### LINKED ISSUE #153: update pull_request_template
In pull_request_template.md
Change
Issue Number with
Fixes #(issue number) so that issue automatically get close on successful merge of PR

@QAZIMAAZARSHAD Please assign me this under DCP21

### PR DESCRIPTION
**Pull request by manasb15**
Fixes #153 
 
#### Describe the changes you've made
Replaced the Issue # format with fixes # in the issue number section of the document.

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [ ] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] Open Source Program names (DCP21)

### CODE REVIEW

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD there is no form for this project I think. Is there?

**Comment by QAZIMAAZARSHAD** [comment]
Refer slack channel.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD Yes got it just now. Also isn't this point in the Checklist sort of redundant if it is happening automatically?
' I have added my name in the contributors list at the end of README.md file.'

**Comment by QAZIMAAZARSHAD** [comment]
Yaa remove that line.

You got 20 points more again.

**Comment by manasb15** [comment]
@QAZIMAAZARSHAD ahaha this is not very fun but as a beginner, it helps me to remember all the git steps and commands so I don't mind. Also you've been very helpful, can we connect on LinkedIn?

**Comment by QAZIMAAZARSHAD** [comment]
Sure

**Pull request merged**
