### PR TITLE
Cursor pointer on hover buttons

### LINKED ISSUE #5: Change cursor to pointer when hovering on buttons

### PR DESCRIPTION
**Pull request by jigar-sable**
#### Issue Number #5 

- fixes #5 

#### Describe the changes you've made

1. I've added pointer cursor to all buttons by adding cursor property.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

#### Test plan
Hover over all buttons as you'll see a pointer cursor there.

#### Checklist
- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] LGM-SOC'21

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@jigar-sable I can't merge your PR. Resolve conflicts.

Update(fetch upstream) your repository with this repository then make changes.

**Comment by jigar-sable** [comment]
> @jigar-sable I can't merge your PR. Resolve conflicts.
> 
> Update(fetch upstream) your repository with this repository then make changes.

Yeah sure I'll resolve the conflicts.

**Comment by QAZIMAAZARSHAD** [comment]
@jigar-sable it's very difficult to review the changes.

259 additions and 257 deletions how to review it.

Make your branch even with the main then make only the necessary changes.

**Review by jigar-sable — COMMENTED** [review]
Ok I was not able fetch upstream so, you may hide the whitespace changes to review. Also, branch doesn't any conflicts now..

**Comment by QAZIMAAZARSHAD** [comment]
Same again.

Screenshot (102)
When you see these line changes to display 5 additions and 8 deletions like something.

Then consider it fine.

**Comment by jigar-sable** [comment]
I got it I'd tried all possible ways fetch upstream, commit new changes, creating new branch then also these so many addition & deletions are showing it's due to whitespace changes after hiding it, it will show minimum changes.

Due to all this conflicts should I close this PR and create new one.

**Comment by jigar-sable** [comment]
Sorry due to few conflicts with the branches I'd created a new PR #34 
@QAZIMAAZARSHAD sir please review #34.

**Pull request closed without merging**
