### PR TITLE
Resolved the issue of Total and the Salary limit by making changes in the FinalProject file.

### LINKED ISSUE #10: Wrong result when taxable income becomes too large
image

### PR DESCRIPTION
**Pull request by techabhi08**
#### Issue Number #10
fixes #10

#### Describe the changes you've made
I have made changes on line 124, 125 and 163,164 to resolve the issue of calculating total for large values. Also changed the integer values to float so that the range of salary can be increased to a great extent.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
The program will run even for very large number but the values should be realistic.  The deduction should be according to the income also. The program will definitely take some time to show the result for very large values.

Screenshot (409)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Screenshot (99)

The same issue again @techabhi08, when taxable income becomes too large the application crashes.

**Comment by techabhi08** [comment]
@QAZIMAAZARSHAD you will have to increase the deduction value according to the annual income. The values should be realistic then it will work. Also it will take long to calculate because the program is made in such way.

**Comment by techabhi08** [comment]
ok I will try it again if i will find any better way

**Comment by QAZIMAAZARSHAD** [comment]
@techabhi08 you have to make separate PR's for separate issues.

Always mention the issue number with PR.


(My mistake for the previous comment, ignore that)
Make another PR for the window issue if you want to score points.

**Comment by techabhi08** [comment]
I am not getting how to do that

**Pull request closed without merging**
