### PR TITLE
Created the code for Splash Screen and added the gif used in splash s…

### LINKED ISSUE #1: Create a splash screen when application opens
A splash screen with the logo of application must appear for 5 seconds when the application start then it should automatically close and then the home page window should appear.

https://cdn.dribbble.com/users/164756/screenshots/14613561/netflix-800x600-with-logo.gif

The splash screen should be like this.

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
…creen

ISSUE #1 

#### Issue Number
fixes #1 

#### Describe the changes you've made
Created the code to add splash screen in the application and added the gif of splash screen

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts.

**Comment by Khushi-sharma07** [comment]
Please check now!

**Comment by QAZIMAAZARSHAD** [comment]
You have changed the entire file.

Make a clean PR, this cannot be reviewed. Update fetch upstream then push changes.

**Comment by Khushi-sharma07** [comment]
Okay

**Pull request closed without merging**
