### PR TITLE
Fixed the issue regarding resetting the input values

### PR DESCRIPTION
**Pull request by Prateek027-S**
#### Issue Number
fixes #
ISSUE #9 

#### Describe the changes you've made
I have used the delete method of entry to delete the input values of e5 and e6 in the delete user defined function. And  I also removed the function call of delete function in the calculate function. 

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Open Source Program name(LGMSOC)

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
@Prateek027-S, I have received another PR for this issue before yours, if your solution is better than the former then only I will merge it.

Wait till I review both PR's.

**Comment by Prateek027-S** [comment]
@QAZIMAAZARSHAD I have also fixed the Issue #4. But I am not able to create a separate PR. It is showing 2 commits under this PR of issue #26 .

**Comment by QAZIMAAZARSHAD** [comment]
Resolve conflicts

**Comment by Prateek027-S** [comment]
@QAZIMAAZARSHAD  It is not showing any kind of conflict.

**Comment by Prateek027-S** [comment]
Okay, @QAZIMAAZARSHAD I resolved the conflicts.

**Comment by QAZIMAAZARSHAD** [comment]
Not resolved

**Comment by QAZIMAAZARSHAD** [comment]
Fetch upstream and create a new PR, it will resolve the issues.

**Pull request closed without merging**
