### PR TITLE
created a yes/no pop-up window when exiting application #8

### PR DESCRIPTION
**Pull request by shashwat-2077**
#### Issue Number #8 
# ISSUE #8 
fixes # created a yes/no pop-up window when exiting the application

#### Describe the changes you've made
I have added an messagebox that pops up at the time of exiting the application asking to confirm whether the user really wants to exit the application

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
`NA`

#### Additional context
image

## worked on the above issue

### CODE REVIEW

**Comment by QAZIMAAZARSHAD** [comment]
The same mistake again @shashwat-2077.

What I want to say is, when I typed #13 it becomes blue. When you hover blue hashtag it shows the issue or pull request associated with the text. You have to do this.

Now, reply by typing #13 so it becomes blue. Let's see did you got it this time or not.

**Comment by shashwat-2077** [comment]
#8

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

One more thing, before working on any issue always ask the project admin to assign you that issue.

**Comment by QAZIMAAZARSHAD** [comment]
@shashwat-2077 ping me in issue number 8 thread so I can assign you.

**Pull request merged**
