### PR TITLE
corrected another bug with sharing

### LINKED ISSUE #126: Another bug with sending with email
The bug is,
when we have entered the correct details and calculated, then if we click on share with email button, we get message like this,

Now in this , the emails are sent in both cases, either we click on OK button or close the dialog box,
but it will work like this
if we click on OK then only it should share the details, otherwise if we close the dialog box, the details should not be shared.

So i want to correct this bug so that if we click on OK button then only it will send details.

And also while sending process is going on we get some print statement in the console, like this,

 so instead of print statement we can show those using message box.

### PR DESCRIPTION
**Pull request by akash-rajak**
#### Issue Number
fixes #126

#### Describe the changes you've made
here i have separated both , showing details pop up window, and the sharing permission asking window.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Checklist

- [ ] I have added my name in the contributors list at the end of README.md file.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] The title of my pull request is a short description of the requested changes.
- [ ] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)

### CODE REVIEW

**Comment by akash-rajak** [comment]
@QAZIMAAZARSHAD , can you please check this one, i have updated

**Comment by QAZIMAAZARSHAD** [comment]
Same result again

**Comment by akash-rajak** [comment]
can you please do one thing, if possible please share the link of code, so that running that code i can get idea of some error,
because its running fine in mine so not am no getting crashing error

**Comment by QAZIMAAZARSHAD** [comment]
> can you please do one thing, if possible please share the link of code, so that running that code i can get idea of some error

How can I share a link?

I am just pushing changes of the PR to the project copy.

**Comment by akash-rajak** [comment]
you will be running the python code, if possible pls send me that code in slack in direct message

**Comment by QAZIMAAZARSHAD** [comment]
https://drive.google.com/drive/folders/1fv8XZNXGiZJKTmpFohbOrJDVowbE5_m1?usp=sharing

Final Projectcopy.py is application after your changes.

**Comment by akash-rajak** [comment]
Can you please tell me that code crashes at which part or it is not running from splash screen only.
Or on giving any input it crashes.
As it is running on mine.

**Comment by QAZIMAAZARSHAD** [comment]
> Can you please tell me that code crashes at which part or it is not runs from from splash screen only.
> Or on giving any input it crashes.
> As it is running on mine.

It crashes as soon as the application opens.

From the start, it closes even before the splash screen opens.

**Comment by akash-rajak** [comment]
In Final Projectcopy.py, line 492 containing this code,
mbox.showinfo("User's tax info ",f"Name: {myname.get()} \n\n Income Tax calculation is: \n\n Oldtax: {old}  Newtax: {new}  Taxsave: {tax_save}")

this line is not indented perfectly, there is a extra single space before mbox
so i think clearing that one space before will work

**Comment by QAZIMAAZARSHAD** [comment]
Already checked.

Indentation is fine.

**Pull request closed without merging**
